services:
  api:
    build: .
    container_name: api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      - PG_HOST=db
      - PG_PASSWORD=$PG_PASSWORD
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:14.2
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: $PG_PASSWORD
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
