name: ci

on: push

jobs:
  set-up:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Set up application
        run: bin/setup
        env:
          PG_HOST: localhost
          PG_PASSWORD: postgres
          PG_USER: postgres
          PG_PORT: 5432


