name: ci

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1
      - name: Build and start container in background
        run: bin/setup && bin/up -d
        env:
          PG_HOST: localhost
          PG_PASSWORD: postgres
          PG_USER: postgres
          PG_PORT: 5432
      - name: Run Tests
        run: bin/test
